// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.scss'

import ContactForm from '../components/contact-form';
import React, { useState, useEffect } from 'react';
import $ from 'jquery';
import { gql } from "@apollo/client";
import client from "../helpers/apollo-client";
import Image from 'next/image';
import ImageLoader from '../components/image-loader';
import { DocumentRenderer } from '@keystone-6/document-renderer';
import { Button } from "@material-tailwind/react";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTag, faClock, faStar } from '@fortawesome/free-solid-svg-icons'

type About = {
  id: String,
  title: String,
  featureImage: String,
  content: JSON,
  guides: [Guide],
  guidesCount: Int
};

export default function Home({ data }: {data:About}) {

  const featureImageStyle = {
    objectFit: 'contain',
    objectPosition: 'center bottom',
    height: '500px',
    width: '630px',
    overflow: 'hidden'
  };

  const tourImageStyle = {
    objectFit: 'cover',
    objectPosition: 'center bottom',
    height: '300px',
    width: '100vw',
    overflow: 'hidden'
  };

  const reviewsStyle = {
    width:'100%',
    height:'100%',
    overflow: 'auto'
  }



  useEffect(() => {
  //  const handleScroll = event => {
      //console.log('window.scrollY', window.scrollY);
      //if (window.scrollY > 0) {
         $('#navbar').addClass('scrolled')
    //   }
    //   else {
    //     $('#navbar').removeClass('scrolled')
    //   }
  //};

    // window.addEventListener('scroll', handleScroll);
    //
    // return () => {
    //   window.removeEventListener('scroll', handleScroll);
    // };
  },[])
  return (
    <div id="home">
    <div className="header-home">
      <div className="left">
        <h1 className="home-title">Join us for <br/>a trip you&apos;ll <br/>never forget.</h1>
        <p>Here at the capetownlocal we always strive for perfection. Our experience is guaranteed to make the best memories.</p>
        <a href="/tours"><Button className="header-button">View Tours</Button></a>
      </div>
    <div className="right">
    <Image
      loader={ImageLoader}
      src="/cptlocalheader.png"
       width={100}
       height={100}
       style={featureImageStyle}/>
    </div>

    </div>
    <div class="info">
      <p>20 <span>years<br/>experience</span></p><span className="separator"></span>
      <p>1000+ <span>trips</span></p><span className="separator"></span>
      <p>10 <span>tour<br/>experiences</span></p><span className="separator"></span>
      <p>4.8<span>overall <br/>rating</span></p>
    </div>
    <h2 className="toursHeading">Most popular tours</h2>
    <div className="tours">
    {data.home.homeTours.map((homeTour) =>(
      <div className="tour" key={homeTour.id}>
        <Image
          loader={ImageLoader}
            src={homeTour.image.url}
           width={100}
           height={100}
           style={tourImageStyle}/>
           <div className="tourContent">
             <h2 className="drop-shadow-md">{homeTour.title}</h2>
             <a href="/tours"><Button className="tour-button">Discover {homeTour.title}</Button></a>
           </div>

      </div>
    ))}
    </div>
    <div className="reviews">
      <div className="left">
        <h2>Reviews</h2>
        <h3>Average rating <span><FontAwesomeIcon icon={faStar} /> </span> 4.8</h3>
        <p>At The Cape Town Local we strive to make your tour as memorable and comfortable as possible. See what others are saying about us.</p>
        <Button className="reviews-button">See All on AIRBNB</Button>
      </div>
      <div className="right">
        <iframe src="https://widget.tagembed.com/77735?view" style={reviewsStyle} frameBorder="0" allowTransparency="true"></iframe>
      </div>

    </div>
    </div>
  )
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
    query GetHome {
       home {
        title
        homeTours {
          title
          price
          duration
          image {
            url
          }
          content {
            document
          }
        }
        featureImage {
            url
          }
      }
    }
    `,
  });
  console.log('data about>>>', data)
  return {
    props: {
      data: data,
    },
  };
}

// <div className={styles.container}>
//   <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>
//
//   <main className={styles.main}>
//     <h1 className={styles.title}>
//       Welcome to <a href="https://nextjs.org">Next.js!</a>
//     </h1>
//
//     <p className={styles.description}>
//       Get started by editing{' '}
//       <code className={styles.code}>pages/index.js</code>
//     </p>
//
//     <div className={styles.grid}>
//       <a href="https://nextjs.org/docs" className={styles.card}>
//         <h2>Documentation &rarr;</h2>
//         <p>Find in-depth information about Next.js features and API.</p>
//       </a>
//
//       <a href="https://nextjs.org/learn" className={styles.card}>
//         <h2>Learn &rarr;</h2>
//         <p>Learn about Next.js in an interactive course with quizzes!</p>
//       </a>
//
//       <a
//         href="https://github.com/vercel/next.js/tree/canary/examples"
//         className={styles.card}
//       >
//         <h2>Examples &rarr;</h2>
//         <p>Discover and deploy boilerplate example Next.js projects.</p>
//       </a>
//
//       <a
//         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//         className={styles.card}
//       >
//         <h2>Deploy &rarr;</h2>
//         <p>
//           Instantly deploy your Next.js site to a public URL with Vercel.
//         </p>
//       </a>
//     </div>
//   </main>
//
//   <footer className={styles.footer}>
//     <a
//       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//       target="_blank"
//       rel="noopener noreferrer"
//     >
//       Powered by{' '}
//       <span className={styles.logo}>
//         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//       </span>
//     </a>
//   </footer>

// <div className="icons">
//   <div className="icon"><FontAwesomeIcon icon={faTag} /><span>{homeTour.price}</span></div>
//   <div className="icon"><FontAwesomeIcon icon={faClock}/><span>{homeTour.duration}</span></div>
// </div>
// <div className="description">
//   <DocumentRenderer document={homeTour.content.document} />
// </div>
